apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ai-agent/deployment.yaml
  - ai-agent/service.yaml
  - ai-agent/route.yaml
  - business-api/deployment.yaml
  - business-api/service.yaml
  - business-api/route.yaml
  - openmetadata/deployment.yaml
  - openmetadata/route.yaml
  - postgresql/deployment.yaml
  - keycloak/deployment.yaml
  - elasticsearch/deployment.yaml
  - kafka/kafka.yaml
  - namespace.yaml
  - rbac.yaml
  - networkpolicy.yaml

labels:
  - pairs:
      app.kubernetes.io/name: enterprise-ai-agent-platform
      app.kubernetes.io/managed-by: argocd
    includeSelectors: false

commonAnnotations:
  app.kubernetes.io/part-of: enterprise-ai-agent-platform
