apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-agent-platform-staging

bases:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: ai-agent-orchestrator
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: business-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2

images:
  - name: quay.io/droneplatform/ai-agent-orchestrator
    newTag: "staging"
  - name: quay.io/droneplatform/business-api
    newTag: "staging"

labels:
  - pairs:
      environment: staging
    includeSelectors: false
